// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
    introductionSidebar: [{ type: "autogenerated", dirName: "introduction" }],
    setupSidebar: [{ type: "autogenerated", dirName: "setup" }],
    infrastructureSidebar: [{ type: "autogenerated", dirName: "infrastructure" }],
    networkingSidebar: [{ type: "autogenerated", dirName: "networking" }],
    devopsSidebar: [{ type: "autogenerated", dirName: "devops" }],
    securitySidebar: [{ type: "autogenerated", dirName: "security" }],
};

export default sidebars;
